# Generated by Django 4.1.3 on 2025-12-10 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_userbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbooking',
            name='ticket_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
